# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: otus
      MONGO_INITDB_ROOT_PASSWORD: otus
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: otus
      ME_CONFIG_MONGODB_ADMINPASSWORD: otus
      ME_CONFIG_MONGODB_URL: mongodb://otus:otus@mongo:27017/